apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: happy-birthday-kush

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: __DOCKERHUB_USERNAME__/happy-birthday-kush
  newName: zerone010101/happy-birthday-kush
  newTag: 2953cdfbd2f8239f8e2b746fe59152aa8cef960e
