apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: happy-birthday-kush

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: __DOCKERHUB_USERNAME__/happy-birthday-kush
  newName: zerone010101/happy-birthday-kush
  newTag: 238df15e3dc0ce60a950bf17c20913b8fbefb0d0
