apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: happy-birthday-kush
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/uplay11/java-app.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: happy-birthday-kush

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
